# Generated by Django 5.2.6 on 2025-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('resident_id', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=100)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
    ]
