# Generated by Django 5.2.6 on 2025-10-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_resident_verification_status_alter_resident_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='proof_residency',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
