# Generated by Django 5.2.6 on 2025-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_resident_middle_name_resident_proof_residency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='current_status',
            field=models.CharField(choices=[('Hired', 'Hired'), ('Not Hired', 'Not Hired'), ('Training', 'Training')], default='Not Hired', max_length=20),
        ),
    ]
