# Generated by Django 5.2.6 on 2025-11-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_resident_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseResident',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'resident',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='residentskill',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='resident',
            name='skills',
        ),
        migrations.AlterField(
            model_name='resident',
            name='verification_status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=20),
        ),
    ]
