# Generated by Django 5.2.6 on 2025-11-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_resident_current_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseResident',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'resident',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='residentskill',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='resident',
            name='skills',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('link_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
