# Generated by Django 5.2.6 on 2025-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_supabaseresident_alter_residentskill_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='verification_status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=20),
        ),
        migrations.AlterModelTable(
            name='residentskill',
            table='resident_skills',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill_list',
        ),
    ]
